### PR TITLE
Inverter only example script

### PR DESCRIPTION
**Pull request by Maikel-K**
I removed the battery part of the script so you can use this script easily to check if your RS485 converter is working.

### CODE REVIEW

**Comment by nmakel** [comment]
Can you explain the difference between this new script and the existing `example.py`? If your inverter has no battery connected the existing examples will work without issue...

**Comment by Maikel-K** [comment]
It wouldn't run on my setup because it was missing the battery🤷🏼‍♂️

**Comment by nmakel** [comment]
It runs fine here, even though I don't have a battery. If you still experience errors, please post them here.

**Comment by nmakel** [comment]
Closing as the behavior that is being changed should not be causing an error. Please open an issue if it does.

**Pull request closed without merging**
